apiVersion: v1
kind: ConfigMap
metadata:
  name: control-gastos-config
  labels:
    app: control-gastos-api
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
  SPRING_H2_CONSOLE_ENABLED: "true"
  SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  INFO_APP_VERSION: "2.0.0"
  JAVA_OPTS: "-Xms256m -Xmx512m"
