apiVersion: v1
kind: Service
metadata:
  name: control-gastos-service
  labels:
    app: control-gastos-api
spec:
  type: NodePort
  selector:
    app: control-gastos-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
